### ISSUE TITLE
Everything works just a few questions

### ISSUE THREAD

**Issue by ioffe-ben** [MyPureCloud/developercenter-tutorials#4]
I have questions in regards to an example in the  tutorial https://github.com/MyPureCloud/developercenter-tutorials/tree/master/calls/javascript

1. How can implement it so every call is not  getting overwritten but remains in the "Queue" table (which is something like the call history)?
2. What is the best way to get a call duration (connectedTime and endTime?)
@KevinGlinski
Thank you!

**Comment by KevinGlinski** [comment]
you can use [GET /api/v2/conversations/calls/history](https://developer.mypurecloud.com/api/rest/v2/conversations/index.html#getConversationsCallsHistory) to get your call history, otherwise if you just wanted the history of the calls since the app was running, you would want to modify the checkQueue()  function and store the conversations in a map on the page.

For call duration you will need to look at the start/end times on the participants.  The first participant (on an inbound call) is the external caller so you can look at that participants start/end
